import { describe, expect, it } from 'vitest';
import {
  moveItem,
  packGrid,
  rowTops,
  spanFor,
  translationFor,
  type GridItem,
} from './dashboardLayoutGrid';

// SMA-336 round 3 (V6). This module is the model the drag preview is computed
// from, so its expectations are written BY HAND from the CSS Grid sparse
// auto-placement rules — never generated by the code under test. If the model
// and the browser ever disagree, it is one of these numbers that is wrong.

const small = (key: string): GridItem => ({ key, cols: 1, rows: 1 });
const medium = (key: string): GridItem => ({ key, cols: 2, rows: 1 });
const large = (key: string): GridItem => ({ key, cols: 2, rows: 2 });

/** A 280px cell, a 200px row and the 20px gutter: one step is 300 x 220. */
const CELL = { width: 280, height: 200, gap: 20 };

/** Every item's pixel displacement when `from` is dropped at `to`. */
function shift(
  items: GridItem[],
  columns: number,
  from: number,
  to: number
): Record<string, [number, number]> {
  const current = packGrid(items, columns);
  const target = packGrid(moveItem(items, from, to), columns);
  const out: Record<string, [number, number]> = {};
  for (const item of items) {
    const t = translationFor(
      current.get(item.key)!,
      target.get(item.key)!,
      CELL.width,
      CELL.height,
      CELL.gap
    );
    out[item.key] = [t.x, t.y];
  }
  return out;
}

/** Every item's cell, as `key: [col, row]`. */
function cells(items: GridItem[], columns: number, flow: 'sparse' | 'dense' = 'sparse') {
  const packed = packGrid(items, columns, flow);
  const out: Record<string, [number, number]> = {};
  for (const item of items) {
    const p = packed.get(item.key)!;
    out[item.key] = [p.col, p.row];
  }
  return out;
}

describe('spanFor — CSS clamps a span to the column count', () => {
  it('keeps the full footprint from two columns up', () => {
    expect(spanFor('small', 4)).toEqual({ cols: 1, rows: 1 });
    expect(spanFor('medium', 4)).toEqual({ cols: 2, rows: 1 });
    expect(spanFor('large', 4)).toEqual({ cols: 2, rows: 2 });
    expect(spanFor('medium', 2)).toEqual({ cols: 2, rows: 1 });
  });

  it('narrows a Medium and a Large to one column on a phone', () => {
    expect(spanFor('medium', 1)).toEqual({ cols: 1, rows: 1 });
    expect(spanFor('large', 1)).toEqual({ cols: 1, rows: 2 });
  });
});

// SMA-437 lot 1, PR A, step A1 (pre-flight D2) — the fourth size, « Pleine
// largeur » on screen, `wide` in the code (V8): 4 × 1, and the same clamp as
// the three others. Two columns on a tablet is A-N12 (« la Pleine largeur
// occupe les deux colonnes »), one on a phone is F10 — both without a line of
// their own, which is what these pin.
describe('spanFor — the Full width (SMA-437, D2)', () => {
  it('takes the four columns of the desktop, the two of a tablet, the one of a phone — on ONE row', () => {
    expect(spanFor('wide', 4)).toEqual({ cols: 4, rows: 1 });
    expect(spanFor('wide', 2)).toEqual({ cols: 2, rows: 1 });
    expect(spanFor('wide', 1)).toEqual({ cols: 1, rows: 1 });
  });
});

describe('packGrid — a Full width opens a row of its own (SMA-437, D2)', () => {
  const wide = (key: string, columns: number): GridItem => ({ key, ...spanFor('wide', columns) });

  it('four columns: the rows before and after it are the other widgets’', () => {
    expect(cells([small('a'), wide('band', 4), small('b')], 4)).toEqual({
      a: [0, 0],
      band: [0, 1],
      b: [0, 2],
    });
  });

  it('four columns: it waits below the lower half of a Large, whose row it cannot share', () => {
    // L holds columns 0-1 of rows 0 and 1; `s` fills column 2 of row 0; the
    // band needs the four columns of one row, and row 1 still has L in it.
    expect(cells([large('L'), small('s'), wide('band', 4)], 4)).toEqual({
      L: [0, 0],
      s: [2, 0],
      band: [0, 2],
    });
  });

  it('two columns — the tablet: both columns, one row (A-N12)', () => {
    expect(cells([small('a'), wide('band', 2), small('b')], 2)).toEqual({
      a: [0, 0],
      band: [0, 1],
      b: [0, 2],
    });
  });
});

describe('packGrid — sparse auto-placement, four columns', () => {
  it('fills a row left to right, then wraps', () => {
    expect(cells([small('a'), small('b'), small('c'), small('d'), small('e')], 4)).toEqual({
      a: [0, 0],
      b: [1, 0],
      c: [2, 0],
      d: [3, 0],
      e: [0, 1],
    });
  });

  it('leaves the hole a too-wide item could not fill, and never backfills it', () => {
    // Three Smalls, then a Medium that needs two columns with one left: the
    // Medium wraps and column 3 of row 0 stays empty for good.
    expect(cells([small('a'), small('b'), small('c'), medium('m'), small('d')], 4)).toEqual({
      a: [0, 0],
      b: [1, 0],
      c: [2, 0],
      m: [0, 1],
      d: [2, 1],
    });
  });

  it('backfills that same hole under `dense`, which the dashboard does NOT use', () => {
    expect(
      cells([small('a'), small('b'), small('c'), medium('m'), small('d')], 4, 'dense')
    ).toEqual({
      a: [0, 0],
      b: [1, 0],
      c: [2, 0],
      m: [0, 1],
      d: [3, 0],
    });
  });

  it('steps over the columns a two-row item holds on the row below', () => {
    expect(cells([large('L'), small('a'), small('b'), small('c')], 4)).toEqual({
      L: [0, 0],
      a: [2, 0],
      b: [3, 0],
      c: [2, 1],
    });
  });
});

describe('the drag preview — every item translated to the cell the drop gives it', () => {
  it('equal sizes: the dragged Small crosses the row, the others close up', () => {
    expect(shift([small('a'), small('b'), small('c'), small('d')], 4, 0, 3)).toEqual({
      a: [900, 0],
      b: [-300, 0],
      c: [-300, 0],
      d: [-300, 0],
    });
  });

  it('a Small dropped where a Large sits pushes the Large one column right', () => {
    const items = [large('L'), small('s1'), small('s2'), small('s3')];
    // Before: L(0,0)-(1,1), s1(2,0), s2(3,0), s3(2,1) — s3 wrapped past the Large.
    // After s3 leads: s3(0,0), L(1,0)-(2,1), s1(3,0), s2(0,1).
    expect(shift(items, 4, 3, 0)).toEqual({
      s3: [-600, -220],
      L: [300, 0],
      s1: [300, 0],
      s2: [-900, 220],
    });
  });

  it('a Large dropped where Smalls sit sends two of them to the next row', () => {
    const items = [small('s1'), small('s2'), small('s3'), small('s4'), large('L')];
    // Before: s1..s4 fill row 0, L wraps to (0,1)-(1,2).
    // After L leads: L(0,0)-(1,1), s1(2,0), s2(3,0), s3(2,1), s4(3,1).
    expect(shift(items, 4, 4, 0)).toEqual({
      s1: [600, 0],
      s2: [600, 0],
      s3: [0, 220],
      s4: [0, 220],
      L: [0, -220],
    });
  });

  it('moving to the right edge', () => {
    const items = [small('a'), medium('m'), small('c')];
    // Before: a(0,0), m(1,0)-(2,0), c(3,0). After a is last: m(0,0)-(1,0), c(2,0), a(3,0).
    expect(shift(items, 4, 0, 2)).toEqual({
      a: [900, 0],
      m: [-300, 0],
      c: [-300, 0],
    });
  });

  it('moving to the left edge', () => {
    const items = [small('a'), medium('m'), small('c')];
    // After c leads: c(0,0), a(1,0), m(2,0)-(3,0).
    expect(shift(items, 4, 2, 0)).toEqual({
      c: [-900, 0],
      a: [300, 0],
      m: [300, 0],
    });
  });

  it('moving onto the last row', () => {
    const items = ['a', 'b', 'c', 'd', 'e', 'f'].map(small);
    // Before: a,b,c,d on row 0; e,f on row 1. After a is last: b,c,d,e / f,a.
    expect(shift(items, 4, 0, 5)).toEqual({
      a: [300, 220],
      b: [-300, 0],
      c: [-300, 0],
      d: [-300, 0],
      e: [900, -220],
      f: [-300, 0],
    });
  });

  it('two columns — the tablet grid', () => {
    const items = [
      { key: 'weather', ...spanFor('medium', 2) },
      { key: 'gardens', ...spanFor('large', 2) },
      { key: 'tips', ...spanFor('small', 2) },
    ];
    // Before: weather fills row 0, gardens rows 1-2, tips wraps to row 3.
    // After tips leads: tips(0,0), weather(0,1), gardens(0,2)-(1,3).
    expect(shift(items, 2, 2, 0)).toEqual({
      tips: [0, -660],
      weather: [0, 220],
      gardens: [0, 220],
    });
  });

  it('one column — the phone grid', () => {
    const items = [
      { key: 's1', ...spanFor('small', 1) },
      { key: 'L', ...spanFor('large', 1) },
      { key: 's2', ...spanFor('small', 1) },
    ];
    // Before: s1(0,0), L(0,1)-(0,2), s2(0,3).
    // After L leads: L(0,0)-(0,1), s1(0,2), s2(0,3).
    expect(shift(items, 1, 1, 0)).toEqual({
      L: [0, -220],
      s1: [0, 440],
      s2: [0, 0],
    });
  });

  it('an unchanged order translates nothing at all', () => {
    const items = [small('a'), large('L'), medium('m'), small('d')];
    expect(shift(items, 4, 2, 2)).toEqual({
      a: [0, 0],
      L: [0, 0],
      m: [0, 0],
      d: [0, 0],
    });
  });
});

// SMA-437 lot 1, PR A, step A4 (pre-flight D6) — the rows of a grid whose
// Full-width rows take the height of their content: the top of each row is
// the sum of the heights and gutters above it. Written by hand.
describe('rowTops — the top of every row, with free-height rows among them (SMA-437, D6)', () => {
  const band = (key: string): GridItem => ({ key, ...spanFor('wide', 4), freeHeight: true });

  it('every row pinned: row r starts at r × (273 + 20)', () => {
    const placed = packGrid([large('a'), medium('b'), medium('c')], 4);
    // a on rows 0-1; b beside it on row 0, c beside it on row 1.
    expect(rowTops(placed, new Map(), 273, 20)).toEqual([0, 293]);
  });

  it('a 180 px band on row 0 moves every row below it up by 273 − 180', () => {
    const placed = packGrid([band('band'), large('a'), large('b')], 4);
    expect(rowTops(placed, new Map([['band', 180]]), 273, 20)).toEqual([0, 200, 493]);
  });

  it('a band between two rows: its own height, the rows around it pinned', () => {
    const placed = packGrid([medium('a'), medium('b'), band('band'), small('c')], 4);
    // a and b on row 0, the band on row 1, c on row 2.
    expect(rowTops(placed, new Map([['band', 130]]), 273, 20)).toEqual([0, 293, 443]);
  });
});

describe('translationFor — a pure delta, no grid origin needed', () => {
  it('counts cells and gutters in both axes', () => {
    expect(
      translationFor({ col: 0, row: 0 }, { col: 2, row: 1 }, 280, 200, 20)
    ).toEqual({ x: 600, y: 220 });
    expect(
      translationFor({ col: 3, row: 2 }, { col: 0, row: 0 }, 280, 200, 20)
    ).toEqual({ x: -900, y: -440 });
  });
});

describe('moveItem', () => {
  it('reorders without mutating its input', () => {
    const items = ['a', 'b', 'c'];
    expect(moveItem(items, 0, 2)).toEqual(['b', 'c', 'a']);
    expect(items).toEqual(['a', 'b', 'c']);
  });
});
