export type Continent =
  | 'africa'
  | 'northAmerica'
  | 'centralAmericaCaribbean'
  | 'southAmerica'
  | 'asia'
  | 'europe'
  | 'oceania';

export const CONTINENT_ORDER: Continent[] = [
  'africa',
  'northAmerica',
  'centralAmericaCaribbean',
  'southAmerica',
  'asia',
  'europe',
  'oceania',
];

/**
 * TDWG level-3 region token -> continent bucket (SMA-39). Keys are the EXACT
 * strings stored in Plants.NativeRegions / IntroducedRegions, including the
 * source data's 20-char truncations (e.g. "North European Russi"). 360 entries.
 */
export const TDWG_TO_CONTINENT: Record<string, Continent> = {
  // africa
  Algeria: 'africa',
  Angola: 'africa',
  Benin: 'africa',
  Botswana: 'africa',
  Burkina: 'africa',
  Burundi: 'africa',
  Cabinda: 'africa',
  Cameroon: 'africa',
  'Cape Provinces': 'africa',
  'Caprivi Strip': 'africa',
  'Central African Repu': 'africa',
  Chad: 'africa',
  Comoros: 'africa',
  Congo: 'africa',
  Djibouti: 'africa',
  Egypt: 'africa',
  'Equatorial Guinea': 'africa',
  Eritrea: 'africa',
  Ethiopia: 'africa',
  'Free State': 'africa',
  Gabon: 'africa',
  Gambia: 'africa',
  Ghana: 'africa',
  Guinea: 'africa',
  'Guinea-Bissau': 'africa',
  'Gulf of Guinea Is.': 'africa',
  'Ivory Coast': 'africa',
  Kenya: 'africa',
  'KwaZulu-Natal': 'africa',
  Lesotho: 'africa',
  Liberia: 'africa',
  Libya: 'africa',
  Madagascar: 'africa',
  Malawi: 'africa',
  Mali: 'africa',
  Mauritania: 'africa',
  Mauritius: 'africa',
  Morocco: 'africa',
  Mozambique: 'africa',
  Namibia: 'africa',
  Niger: 'africa',
  Nigeria: 'africa',
  'Northern Provinces': 'africa',
  Réunion: 'africa',
  Rodrigues: 'africa',
  Rwanda: 'africa',
  Senegal: 'africa',
  Seychelles: 'africa',
  'Sierra Leone': 'africa',
  Socotra: 'africa',
  Somalia: 'africa',
  Sudan: 'africa',
  Swaziland: 'africa',
  Tanzania: 'africa',
  Togo: 'africa',
  Tunisia: 'africa',
  Uganda: 'africa',
  'Western Sahara': 'africa',
  Zambia: 'africa',
  Zaïre: 'africa',
  Zimbabwe: 'africa',
  Aldabra: 'africa',
  'Chagos Archipelago': 'africa',
  'Canary Is.': 'africa',
  'Cape Verde': 'africa',
  Ascension: 'africa',
  'St.Helena': 'africa',
  'Tristan da Cunha': 'africa',
  // northAmerica
  Alabama: 'northAmerica',
  Alaska: 'northAmerica',
  Arizona: 'northAmerica',
  Arkansas: 'northAmerica',
  California: 'northAmerica',
  Colorado: 'northAmerica',
  Connecticut: 'northAmerica',
  Delaware: 'northAmerica',
  'District of Columbia': 'northAmerica',
  Florida: 'northAmerica',
  Georgia: 'northAmerica',
  Idaho: 'northAmerica',
  Illinois: 'northAmerica',
  Indiana: 'northAmerica',
  Iowa: 'northAmerica',
  Kansas: 'northAmerica',
  Kentucky: 'northAmerica',
  Louisiana: 'northAmerica',
  Maine: 'northAmerica',
  Maryland: 'northAmerica',
  Masachusettes: 'northAmerica',
  Michigan: 'northAmerica',
  Minnesota: 'northAmerica',
  Mississippi: 'northAmerica',
  Missouri: 'northAmerica',
  Montana: 'northAmerica',
  Nebraska: 'northAmerica',
  Nevada: 'northAmerica',
  'New Hampshire': 'northAmerica',
  'New Jersey': 'northAmerica',
  'New Mexico': 'northAmerica',
  'New York': 'northAmerica',
  'North Carolina': 'northAmerica',
  'North Dakota': 'northAmerica',
  Ohio: 'northAmerica',
  Oklahoma: 'northAmerica',
  Oregon: 'northAmerica',
  Pennsylvania: 'northAmerica',
  'Rhode I.': 'northAmerica',
  'South Carolina': 'northAmerica',
  'South Dakota': 'northAmerica',
  Tennessee: 'northAmerica',
  Texas: 'northAmerica',
  Utah: 'northAmerica',
  Vermont: 'northAmerica',
  Virginia: 'northAmerica',
  Washington: 'northAmerica',
  'West Virginia': 'northAmerica',
  Wisconsin: 'northAmerica',
  Wyoming: 'northAmerica',
  Alberta: 'northAmerica',
  'British Columbia': 'northAmerica',
  Labrador: 'northAmerica',
  Manitoba: 'northAmerica',
  'New Brunswick': 'northAmerica',
  Newfoundland: 'northAmerica',
  'Northwest Territorie': 'northAmerica',
  'Nova Scotia': 'northAmerica',
  Nunavut: 'northAmerica',
  Ontario: 'northAmerica',
  'Prince Edward I.': 'northAmerica',
  Québec: 'northAmerica',
  Saskatchewan: 'northAmerica',
  Yukon: 'northAmerica',
  'Mexico Central': 'northAmerica',
  'Mexico Gulf': 'northAmerica',
  'Mexico Northeast': 'northAmerica',
  'Mexico Northwest': 'northAmerica',
  'Mexico Southeast': 'northAmerica',
  'Mexico Southwest': 'northAmerica',
  Greenland: 'northAmerica',
  Bermuda: 'northAmerica',
  'Aleutian Is.': 'northAmerica',
  // centralAmericaCaribbean
  Belize: 'centralAmericaCaribbean',
  Guatemala: 'centralAmericaCaribbean',
  Honduras: 'centralAmericaCaribbean',
  'El Salvador': 'centralAmericaCaribbean',
  Nicaragua: 'centralAmericaCaribbean',
  'Costa Rica': 'centralAmericaCaribbean',
  Panamá: 'centralAmericaCaribbean',
  'Central American Pac': 'centralAmericaCaribbean',
  Cuba: 'centralAmericaCaribbean',
  Bahamas: 'centralAmericaCaribbean',
  Jamaica: 'centralAmericaCaribbean',
  Haiti: 'centralAmericaCaribbean',
  'Dominican Republic': 'centralAmericaCaribbean',
  'Puerto Rico': 'centralAmericaCaribbean',
  'Cayman Is.': 'centralAmericaCaribbean',
  'Turks-Caicos Is.': 'centralAmericaCaribbean',
  'Leeward Is.': 'centralAmericaCaribbean',
  'Windward Is.': 'centralAmericaCaribbean',
  'Trinidad-Tobago': 'centralAmericaCaribbean',
  Aruba: 'centralAmericaCaribbean',
  'Netherlands Antilles': 'centralAmericaCaribbean',
  'Venezuelan Antilles': 'centralAmericaCaribbean',
  'Southwest Caribbean': 'centralAmericaCaribbean',
  // southAmerica
  Colombia: 'southAmerica',
  Venezuela: 'southAmerica',
  Guyana: 'southAmerica',
  Suriname: 'southAmerica',
  'French Guiana': 'southAmerica',
  Ecuador: 'southAmerica',
  Peru: 'southAmerica',
  Bolivia: 'southAmerica',
  Paraguay: 'southAmerica',
  Uruguay: 'southAmerica',
  'Brazil North': 'southAmerica',
  'Brazil Northeast': 'southAmerica',
  'Brazil South': 'southAmerica',
  'Brazil Southeast': 'southAmerica',
  'Brazil West-Central': 'southAmerica',
  'Argentina Northeast': 'southAmerica',
  'Argentina Northwest': 'southAmerica',
  'Argentina South': 'southAmerica',
  'Chile Central': 'southAmerica',
  'Chile North': 'southAmerica',
  'Chile South': 'southAmerica',
  Galápagos: 'southAmerica',
  'Juan Fernández Is.': 'southAmerica',
  'Desventurados Is.': 'southAmerica',
  'Falkland Is.': 'southAmerica',
  'South Georgia': 'southAmerica',
  // asia
  Iran: 'asia',
  Iraq: 'asia',
  'Saudi Arabia': 'asia',
  Yemen: 'asia',
  Oman: 'asia',
  Kuwait: 'asia',
  'Gulf States': 'asia',
  'Lebanon-Syria': 'asia',
  Palestine: 'asia',
  Sinai: 'asia',
  Cyprus: 'asia',
  'East Aegean Is.': 'asia',
  Transcaucasus: 'asia',
  'North Caucasus': 'asia',
  Turkey: 'asia',
  Kazakhstan: 'asia',
  Uzbekistan: 'asia',
  Turkmenistan: 'asia',
  Tadzhikistan: 'asia',
  Kirgizstan: 'asia',
  Afghanistan: 'asia',
  Altay: 'asia',
  Amur: 'asia',
  Buryatiya: 'asia',
  Chita: 'asia',
  Irkutsk: 'asia',
  Kamchatka: 'asia',
  Khabarovsk: 'asia',
  Krasnoyarsk: 'asia',
  'Kuril Is.': 'asia',
  Primorye: 'asia',
  Sakhalin: 'asia',
  'West Siberia': 'asia',
  Yakutskiya: 'asia',
  Tuva: 'asia',
  Qinghai: 'asia',
  Tibet: 'asia',
  Xinjiang: 'asia',
  'Inner Mongolia': 'asia',
  Manchuria: 'asia',
  Mongolia: 'asia',
  Magadan: 'asia',
  'China North-Central': 'asia',
  'China South-Central': 'asia',
  'China Southeast': 'asia',
  Korea: 'asia',
  Japan: 'asia',
  Taiwan: 'asia',
  Hainan: 'asia',
  'Nansei-shoto': 'asia',
  'Ogasawara-shoto': 'asia',
  'Kazan-retto': 'asia',
  India: 'asia',
  Pakistan: 'asia',
  Bangladesh: 'asia',
  'Sri Lanka': 'asia',
  Nepal: 'asia',
  'East Himalaya': 'asia',
  'West Himalaya': 'asia',
  Assam: 'asia',
  Maldives: 'asia',
  'Laccadive Is.': 'asia',
  'Andaman Is.': 'asia',
  'Nicobar Is.': 'asia',
  Myanmar: 'asia',
  Thailand: 'asia',
  Laos: 'asia',
  Cambodia: 'asia',
  Vietnam: 'asia',
  Malaya: 'asia',
  Sumatera: 'asia',
  Jawa: 'asia',
  Borneo: 'asia',
  Sulawesi: 'asia',
  Maluku: 'asia',
  'Lesser Sunda Is.': 'asia',
  Philippines: 'asia',
  'South China Sea': 'asia',
  // europe
  Albania: 'europe',
  Austria: 'europe',
  Baleares: 'europe',
  'Baltic States': 'europe',
  Belarus: 'europe',
  Belgium: 'europe',
  Bulgaria: 'europe',
  Corse: 'europe',
  Czechoslovakia: 'europe',
  Denmark: 'europe',
  Finland: 'europe',
  France: 'europe',
  Germany: 'europe',
  'Great Britain': 'europe',
  Greece: 'europe',
  Hungary: 'europe',
  Ireland: 'europe',
  Italy: 'europe',
  Kriti: 'europe',
  Krym: 'europe',
  Netherlands: 'europe',
  Norway: 'europe',
  Poland: 'europe',
  Portugal: 'europe',
  Romania: 'europe',
  Sardegna: 'europe',
  Sicilia: 'europe',
  Spain: 'europe',
  Sweden: 'europe',
  Switzerland: 'europe',
  Ukraine: 'europe',
  Yugoslavia: 'europe',
  'Turkey-in-Europe': 'europe',
  'Central European Rus': 'europe',
  'East European Russia': 'europe',
  'North European Russi': 'europe',
  'Northwest European R': 'europe',
  'South European Russi': 'europe',
  Azores: 'europe',
  Madeira: 'europe',
  Selvagens: 'europe',
  Føroyar: 'europe',
  Iceland: 'europe',
  Svalbard: 'europe',
  // oceania
  'New South Wales': 'oceania',
  Queensland: 'oceania',
  'South Australia': 'oceania',
  Tasmania: 'oceania',
  Victoria: 'oceania',
  'Western Australia': 'oceania',
  'Northern Territory': 'oceania',
  'New Zealand North': 'oceania',
  'New Zealand South': 'oceania',
  'Chatham Is.': 'oceania',
  'Kermadec Is.': 'oceania',
  'Antipodean Is.': 'oceania',
  Fiji: 'oceania',
  Samoa: 'oceania',
  Tonga: 'oceania',
  Tuvalu: 'oceania',
  Nauru: 'oceania',
  Vanuatu: 'oceania',
  'New Caledonia': 'oceania',
  'Solomon Is.': 'oceania',
  'New Guinea': 'oceania',
  'Bismarck Archipelago': 'oceania',
  'Santa Cruz Is.': 'oceania',
  'Caroline Is.': 'oceania',
  Marianas: 'oceania',
  'Marshall Is.': 'oceania',
  'Gilbert Is.': 'oceania',
  'Phoenix Is.': 'oceania',
  'Line Is.': 'oceania',
  'Wake I.': 'oceania',
  'Cook Is.': 'oceania',
  Niue: 'oceania',
  'Tokelau-Manihiki': 'oceania',
  'Society Is.': 'oceania',
  Tuamotu: 'oceania',
  'Tubuai Is.': 'oceania',
  Marquesas: 'oceania',
  'Pitcairn Is.': 'oceania',
  'Easter Is.': 'oceania',
  'Wallis-Futuna Is.': 'oceania',
  'Norfolk Is.': 'oceania',
  Hawaii: 'oceania',
  'Christmas I.': 'oceania',
  Kerguelen: 'oceania',
  'Crozet Is.': 'oceania',
  'Amsterdam-St.Paul Is': 'oceania',
  'Marion-Prince Edward': 'oceania',
  'Macquarie Is.': 'oceania',
};

/**
 * Map a list of raw TDWG region tokens to the DISTINCT continents they cover,
 * in CONTINENT_ORDER. Unknown tokens are ignored.
 */
export function regionsToContinents(regions: string[]): Continent[] {
  const set = new Set<Continent>();
  for (const r of regions) {
    const c = TDWG_TO_CONTINENT[r];
    if (c) set.add(c);
  }
  return CONTINENT_ORDER.filter((c) => set.has(c));
}
